# Generated by Django 2.0 on 2019-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_recharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_transaction_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='response_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='response_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('PAYU', 'Payumoney'), ('PAYTM', 'Paytm')], default='PAYU', max_length=5),
        ),
    ]
