# Generated by Django 2.0 on 2019-08-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190802_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_txnid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='response_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='response_message',
        ),
    ]
