# Generated by Django 2.0 on 2019-08-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='gateway',
            field=models.CharField(choices=[('PAYU', 'Payumoney'), ('PAYTM', 'Paytm')], default='PAYU', max_length=5),
        ),
    ]
