# Generated by Django 2.0 on 2019-08-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0002_recharge_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recharge',
            name='gateway',
            field=models.CharField(choices=[('PAYU', 'Payumoney'), ('PAYTM', 'Paytm')], max_length=5),
        ),
    ]
